# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

"""Extract per-batch, per-attention-layer timings from torch profiler traces.

This script parses Chrome trace JSON files generated by torch profiler
(`tensorboard_trace_handler`) and outputs:
1) batch summary CSV
2) batch-layer detail CSV
3) JSON report

It relies on vLLM's worker-level batch annotation names:
  execute_context_<n_ctx_reqs>(<n_ctx_tokens>)_generation_<n_gen_reqs>(<n_gen_tokens>)
"""

from __future__ import annotations

import argparse
import csv
import gzip
import json
import re
from bisect import bisect_left
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any


BATCH_NAME_RE = re.compile(
    r"^execute_context_(?P<ctx_reqs>\d+)\((?P<ctx_tokens>\d+)\)"
    r"_generation_(?P<gen_reqs>\d+)\((?P<gen_tokens>\d+)\)$"
)
MODULE_NAME_RE = re.compile(r"""['"]Module['"]\s*:\s*['"]([^'"]+)['"]""")


@dataclass
class TraceEvent:
    name: str
    ts_us: float
    dur_us: float

    @property
    def end_us(self) -> float:
        return self.ts_us + self.dur_us


@dataclass
class BatchMarker:
    batch_idx: int
    ts_us: float
    dur_us: float
    ctx_reqs: int | None
    ctx_tokens: int | None
    gen_reqs: int | None
    gen_tokens: int | None

    @property
    def end_us(self) -> float:
        return self.ts_us + self.dur_us


def _open_json_file(path: Path) -> dict[str, Any]:
    if path.suffix == ".gz":
        with gzip.open(path, "rt", encoding="utf-8") as f:
            return json.load(f)
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _find_trace_files(trace_path: Path) -> list[Path]:
    if trace_path.is_file():
        return [trace_path]
    if not trace_path.is_dir():
        raise FileNotFoundError(f"Trace path not found: {trace_path}")

    patterns = (
        "**/*.pt.trace.json",
        "**/*.pt.trace.json.gz",
        "**/*.json",
        "**/*.json.gz",
    )
    files: list[Path] = []
    for pattern in patterns:
        files.extend(trace_path.glob(pattern))
    # de-dup while preserving deterministic order
    unique_files = sorted(set(files))
    return unique_files


def _iter_complete_events(trace: dict[str, Any]) -> list[TraceEvent]:
    events = trace.get("traceEvents", [])
    parsed: list[TraceEvent] = []
    for ev in events:
        if not isinstance(ev, dict):
            continue
        # complete event in Chrome trace format
        if ev.get("ph") != "X":
            continue
        name = ev.get("name")
        ts = ev.get("ts")
        dur = ev.get("dur")
        if not isinstance(name, str):
            continue
        if not isinstance(ts, (int, float)) or not isinstance(dur, (int, float)):
            continue
        if dur < 0:
            continue
        parsed.append(TraceEvent(name=name, ts_us=float(ts), dur_us=float(dur)))
    parsed.sort(key=lambda e: e.ts_us)
    return parsed


def _parse_batch_marker(name: str) -> tuple[int, int, int, int] | None:
    m = BATCH_NAME_RE.match(name)
    if m is None:
        return None
    return (
        int(m.group("ctx_reqs")),
        int(m.group("ctx_tokens")),
        int(m.group("gen_reqs")),
        int(m.group("gen_tokens")),
    )


def _extract_module_name(event_name: str) -> str | None:
    m = MODULE_NAME_RE.search(event_name)
    if m:
        return m.group(1)
    return None


def _event_matches_attention(
    event_name: str,
    module_name: str | None,
    attention_re: re.Pattern[str],
) -> tuple[bool, str]:
    if _parse_batch_marker(event_name) is not None:
        return False, ""

    # Prefer module path if this is a structured NVTX marker.
    candidate = module_name or event_name
    if attention_re.search(candidate) is None:
        return False, ""

    return True, candidate


def _build_batch_markers(events: list[TraceEvent]) -> list[BatchMarker]:
    batches: list[BatchMarker] = []
    for ev in events:
        parsed = _parse_batch_marker(ev.name)
        if parsed is None:
            continue
        ctx_reqs, ctx_tokens, gen_reqs, gen_tokens = parsed
        batches.append(
            BatchMarker(
                batch_idx=len(batches),
                ts_us=ev.ts_us,
                dur_us=ev.dur_us,
                ctx_reqs=ctx_reqs,
                ctx_tokens=ctx_tokens,
                gen_reqs=gen_reqs,
                gen_tokens=gen_tokens,
            )
        )

    if batches:
        return batches

    # Fallback: treat each forward scope as one batch.
    for ev in events:
        if ev.name == "gpu_model_runner: forward":
            batches.append(
                BatchMarker(
                    batch_idx=len(batches),
                    ts_us=ev.ts_us,
                    dur_us=ev.dur_us,
                    ctx_reqs=None,
                    ctx_tokens=None,
                    gen_reqs=None,
                    gen_tokens=None,
                )
            )
    return batches


def _collect_attention_events(
    events: list[TraceEvent], attention_re: re.Pattern[str]
) -> list[tuple[TraceEvent, str]]:
    out: list[tuple[TraceEvent, str]] = []
    for ev in events:
        module_name = _extract_module_name(ev.name)
        matched, layer_name = _event_matches_attention(ev.name, module_name, attention_re)
        if matched:
            out.append((ev, layer_name))
    out.sort(key=lambda x: x[0].ts_us)
    return out


def _collect_forward_events(events: list[TraceEvent]) -> list[TraceEvent]:
    out = [ev for ev in events if ev.name == "gpu_model_runner: forward"]
    out.sort(key=lambda e: e.ts_us)
    return out


def _aggregate(
    batches: list[BatchMarker],
    attention_events: list[tuple[TraceEvent, str]],
    forward_events: list[TraceEvent],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    attn_starts = [ev.ts_us for ev, _ in attention_events]
    forward_starts = [ev.ts_us for ev in forward_events]

    batch_rows: list[dict[str, Any]] = []
    layer_rows: list[dict[str, Any]] = []

    for batch in batches:
        layer_dur_us: dict[str, float] = defaultdict(float)
        layer_calls: dict[str, int] = defaultdict(int)

        # Sum per-layer attention durations with event start in the batch window.
        i = bisect_left(attn_starts, batch.ts_us)
        while i < len(attention_events):
            ev, layer_name = attention_events[i]
            if ev.ts_us >= batch.end_us:
                break
            layer_dur_us[layer_name] += ev.dur_us
            layer_calls[layer_name] += 1
            i += 1

        forward_dur_us = 0.0
        j = bisect_left(forward_starts, batch.ts_us)
        while j < len(forward_events):
            ev = forward_events[j]
            if ev.ts_us >= batch.end_us:
                break
            forward_dur_us += ev.dur_us
            j += 1

        total_attn_us = sum(layer_dur_us.values())
        batch_rows.append(
            {
                "batch_idx": batch.batch_idx,
                "ctx_reqs": batch.ctx_reqs,
                "ctx_tokens": batch.ctx_tokens,
                "gen_reqs": batch.gen_reqs,
                "gen_tokens": batch.gen_tokens,
                "batch_dur_ms": batch.dur_us / 1000.0,
                "forward_dur_ms": forward_dur_us / 1000.0,
                "attention_total_ms": total_attn_us / 1000.0,
                "attention_event_calls": int(sum(layer_calls.values())),
                "attention_unique_layers": int(len(layer_calls)),
            }
        )

        for layer_name, dur_us in sorted(
            layer_dur_us.items(), key=lambda x: x[1], reverse=True
        ):
            calls = layer_calls[layer_name]
            layer_rows.append(
                {
                    "batch_idx": batch.batch_idx,
                    "layer_name": layer_name,
                    "calls": calls,
                    "total_ms": dur_us / 1000.0,
                    "avg_ms": (dur_us / calls) / 1000.0 if calls > 0 else 0.0,
                }
            )

    return batch_rows, layer_rows


def _path_stem(path: Path) -> str:
    name = path.name
    for suffix in (".pt.trace.json.gz", ".pt.trace.json", ".json.gz", ".json"):
        if name.endswith(suffix):
            return name[: -len(suffix)]
    return path.stem


def _write_csv(path: Path, rows: list[dict[str, Any]], fields: list[str]) -> None:
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def process_trace_file(
    trace_file: Path, out_dir: Path, attention_re: re.Pattern[str]
) -> dict[str, Any]:
    trace_json = _open_json_file(trace_file)
    events = _iter_complete_events(trace_json)
    batches = _build_batch_markers(events)
    attn_events = _collect_attention_events(events, attention_re)
    forward_events = _collect_forward_events(events)

    batch_rows, layer_rows = _aggregate(batches, attn_events, forward_events)

    stem = _path_stem(trace_file)
    batch_csv = out_dir / f"{stem}.batch_summary.csv"
    layer_csv = out_dir / f"{stem}.batch_layer_attention.csv"
    report_json = out_dir / f"{stem}.attention_report.json"

    _write_csv(
        batch_csv,
        batch_rows,
        fields=[
            "batch_idx",
            "ctx_reqs",
            "ctx_tokens",
            "gen_reqs",
            "gen_tokens",
            "batch_dur_ms",
            "forward_dur_ms",
            "attention_total_ms",
            "attention_event_calls",
            "attention_unique_layers",
        ],
    )
    _write_csv(
        layer_csv,
        layer_rows,
        fields=[
            "batch_idx",
            "layer_name",
            "calls",
            "total_ms",
            "avg_ms",
        ],
    )

    report = {
        "trace_file": str(trace_file),
        "num_complete_events": len(events),
        "num_batches": len(batch_rows),
        "num_attention_events": len(attn_events),
        "outputs": {
            "batch_summary_csv": str(batch_csv),
            "batch_layer_attention_csv": str(layer_csv),
            "report_json": str(report_json),
        },
        "notes": [
            "Batch markers are parsed from worker annotation names.",
            "If markers are missing, gpu_model_runner: forward scopes are used as fallback batches.",
            "Attention events are selected by regex over module name/event name.",
        ],
    }

    with report_json.open("w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)

    return report


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description=(
            "Extract per-batch per-attention-layer timing from torch profiler traces."
        )
    )
    p.add_argument(
        "--trace-path",
        type=Path,
        required=True,
        help="Trace file (.json/.json.gz) or directory containing trace files.",
    )
    p.add_argument(
        "--output-dir",
        type=Path,
        default=Path("trace_attention_reports"),
        help="Directory to write CSV/JSON outputs.",
    )
    p.add_argument(
        "--attention-pattern",
        type=str,
        default=r"(attn|attention)",
        help=(
            "Case-insensitive regex to identify attention layer events by name. "
            "Default: (attn|attention)"
        ),
    )
    return p


def main() -> None:
    args = build_parser().parse_args()
    attention_re = re.compile(args.attention_pattern, re.IGNORECASE)

    trace_files = _find_trace_files(args.trace_path)
    if not trace_files:
        raise RuntimeError(f"No trace files found under: {args.trace_path}")

    args.output_dir.mkdir(parents=True, exist_ok=True)

    reports = []
    for trace_file in trace_files:
        report = process_trace_file(trace_file, args.output_dir, attention_re)
        reports.append(report)
        print(
            f"[OK] {trace_file} -> batches={report['num_batches']}, "
            f"attention_events={report['num_attention_events']}"
        )

    index_path = args.output_dir / "index.json"
    with index_path.open("w", encoding="utf-8") as f:
        json.dump({"reports": reports}, f, indent=2)
    print(f"[DONE] wrote report index: {index_path}")


if __name__ == "__main__":
    main()
